### ISSUE TITLE
Python 3 libstruct wrapper fails to load stoichiometry matrix

### ISSUE THREAD

**Issue by yosefmaru** [sys-bio/Libstructural#21]
When trying to load a stoichiometry matrix model, a Type Error is thrown as shown below.

```
Traceback (most recent call last):
  File "<input>", line 7, in <module>
  File "<string>", line 175, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/structural-2.0.0.post2-py3.6.egg/structural/structural.py", line 1643, in loadStoichiometryMatrix
    m.set (i, j, data[i][j])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/structural-2.0.0.post2-py3.6.egg/structural/structural.py", line 2278, in set
    return _structural.DoubleMatrix_set(self, row, col, value)
TypeError: in method 'DoubleMatrix_set', argument 4 of type 'double'
```

I tried modifying the libstructural.i. I believe the issue is on the code block of line 713 to 724. But, I might be wrong. This issue appears only with python 3 version of the wrapper.

**Comment by yosefmaru** [comment]
The python wrapper can be found in the Win_64/3 folder from the repo.

**Comment by hsauro** [comment]
You'll have to fix this, I don't have access to my laptop.

H

**Comment by fbergmann** [comment]
This was working fine,  as far as python is concerned you tried to insert something that was not a double into a double matrix, and the type checks told you so. In the commit above i force the values to double, so the integer example you had is working now in python 3 as well

**Comment by yosefmaru** [comment]
It works now. Thanks

Yosef
